//  THERE ARE MORE THAN ONE TYPE OF INHERITANCE IN C++

// 1 . --> WHEN FROM ONE CLASS ONLY ONE OTHER CLASS INHERITS IS CALLED SIMPLE OR SINGLE INHERITANCE.

// 2 . --> MORE THAN ONE CLASS ARE INHERITING FROM THE SAME CLASS IS CALLED HIERARCHICAL INHERITANCE.

// 3 . --> IF THERE IS A CLASS (A) FROM THAT CLASS (B) IS INHERITING FORM THAT CALSS (C) IS INHARITING 
//         THAT IS CALLED MULTILEVEL INHERITANCE

// 4 . --> IF THERE IS A CLASS (A) AND A CLASS (B) AND (C) IS INHERITING FROM BOTH OF THEM THEN THIS 
//         IS CALLED MULTIPLE INHERITANCE

//  MULTIPLE INHERITANCE --> MEANS A CLASS CAN INHERIT FROM MORE THAN ONE CLASSES

